Default: &defaults
  approot: "/yesodbookjp/test"
  port: 4000

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://melpon.org/yesodbookjp"
  port: 4100
  <<: *defaults
